version: "3.9"

services:
 land_obs_cache:
  restart: unless-stopped
  build: .
  command: python NWS_Land_Cache_svc.py -d 900
  volumes:
  - ./Data:/app/Data

 land_obs_api:
  restart: unless-stopped
  build: .
  command: python NWS_API.py
  ports:
  - "5000:5000"
  volumes:
  - ./Data:/app/Data

 land_forecast_cache:
  restart: unless-stopped
  build: .
  command: python NWS_Land_Forecast_svc.py -d 3600
  volumes:
  - ./Data:/app/Data

 land_forecast_api:
  restart: unless-stopped
  build: .
  command: python SG_Land_Forecast_API.py
  ports:
  - "5008:5008"
  volumes:
  - ./Data:/app/Data
  
 water_forecast_cache:
  restart: unless-stopped
  build: .
  command: python SG_Water_Forecast_svc.py -d 3600
  volumes:
  - ./Data:/app/Data
  
 water_forecast_api:
  restart: unless-stopped
  build: .
  command: python SG_Water_Forecast_API.py
  ports:
  - "5022:5022"
  volumes:
  - ./Data:/app/Data
  
 historical_precip_cache:
  restart: unless-stopped
  build: .
  command: python SG_Historical_Rainfall_svc.py -d 3600
  volumes:
  - ./Data:/app/Data
  
 historical_precip_api:
  restart: unless-stopped
  build: .
  command: python SG_Precip_Historical_API.py
  ports:
  - "5012:5012"
  volumes:
  - ./Data:/app/Data
