server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/observations {
        proxy_pass http://land_obs_api:5000/observations;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/forecast {
        proxy_pass http://land_forecast_api:5008/forecast;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/historicalPrecip {
        proxy_pass http://historical_precip_api:5012/historicalPrecip;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/waterStations {
        proxy_pass http://water_forecast_api:5022/waterStations;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/waterStationForecast {
        proxy_pass http://water_forecast_api:5022/waterStationForecast;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}